### ISSUE TITLE
Skewed T-fit throwing AttributeError while reading CheckBox

### ISSUE THREAD

**Issue by knazran** [IMFGAR/GaR#2]
### Problem Description
Following the steps outlined in the 'How to start' documentation, upon executing Step 3: Skewed T-Fit, it throws the following error:
```
---------------------------
Error
---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "d:\users\%%%%%\gar\GAR\tsfit\tsfit_main.py", line 61, in do_tsfit

    dict_input_tsfit, df_tsfit_collections = prerun_tsfit(debug=debug)

  File "d:\users\%%%%%\gar\GAR\tsfit\tsfit_main.py", line 104, in prerun_tsfit

    dict_input_tsfit = read_parameters_tsfit()

  File "d:\users\%%%%%\gar\GAR\tsfit\tsfit_main.py", line 191, in read_parameters_tsfit

    e=c.value

  File "D:\Users\%%%%%\Python\Python37\site-packages\win32com\client\__init__.py", line 473, in __getattr__

    raise AttributeError("'%s' object has no attribute '%s'" % (repr(self), attr))

AttributeError: '<win32com.gen_py.Microsoft Excel 16.0 Object Library.CheckBox instance at 0x2472374577544>' object has no attribute 'value'
```

It was tested on Windows 10 with Anaconda Python. below are the versions of the required library:
```
pywin32==228
numpy==1.16.5
pandas==0.25.1
matplotlib==3.1.1
statsmodels==0.10.1
scipy==1.3.1
xlwings==0.15.10
seaborn==0.9.0
python_dateutil==2.8.1
scikit_learn==0.23.2
```

**Comment by naivej** [comment]
I run into the same problem recently although everything worked perfectly a few months back.
My temporary solution is to comment out lines 188-193, 195, 197 in tsfit_main.py
and manually assign Ture/False to line 194, 196, 197.
However, in my experience, xlwings still has troubles sending key results (stored in variable cond_quant, df_pdf, and res) to Excel, _UNLESS_ I go line by line (542-545) in debug mode.

**Comment by romainlafarguette** [comment]
Thank you very much for your comments. We are aware of the discrepancy between the newest versions of xlwings and pandas and the one we are using. Have you tried running it under the uploaded version, 2 months ago?

**Comment by romainlafarguette** [comment]
I am closing it for now, will reopen if necessary
